name: rectify
description: >-
  Extension methods to make Rect pleasant and convenient to work with.
version: 0.2.1
homepage: https://github.com/jpnurmi/dart_rectify
repository: https://github.com/jpnurmi/dart_rectify
issue_tracker: https://github.com/jpnurmi/dart_rectify/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
